const CLOUD={available:false,busy:false};
const adminKey=()=>sessionStorage.getItem('cw-admin-key')||'';
function cloudHeaders(json=false){const h={};if(json)h['content-type']='application/json';if(adminKey())h['x-admin-key']=adminKey();return h}
function cloudMessage(msg,kind=''){const el=document.getElementById('cloudState');if(!el)return;el.className='status'+(kind?' '+kind:'');el.textContent=msg}
function injectCloudStyles(){if(document.getElementById('cloudSyncStyles'))return;const s=document.createElement('style');s.id='cloudSyncStyles';s.textContent=`
.cloudTopActions{display:flex;align-items:center;gap:8px;flex-wrap:wrap;justify-content:flex-end}.cloudTopBtn{border:1px solid #b8d0c7;background:#fff;color:#2d6657;border-radius:999px;padding:8px 12px;font-weight:900;cursor:pointer;box-shadow:0 2px 8px rgba(36,34,29,.04)}.cloudTopBtn:hover{background:#e7f1ed}.cloudTopBtn.online{background:#e7f1ed}.cloudBackdrop{position:fixed;inset:0;background:rgba(25,28,26,.28);z-index:9998;display:none}.cloudBackdrop.open{display:block}.cloudModal{position:fixed;top:74px;right:24px;width:min(430px,calc(100vw - 28px));max-height:calc(100vh - 100px);overflow:auto;background:#fff;border:1px solid #dedbd3;border-radius:18px;padding:18px;z-index:9999;box-shadow:0 24px 70px rgba(20,30,25,.22);display:none}.cloudModal.open{display:block}.cloudModalHead{display:flex;align-items:center;justify-content:space-between;gap:12px}.cloudModalHead h2{margin:0}.cloudClose{background:#efede7;width:36px;height:36px;padding:0;border-radius:50%;font-size:18px}.cloudHint{font-size:12px;color:#6c6b65;margin:8px 0 0}.cloudKeyRow{display:grid;gap:6px;margin-top:14px}.cloudKeyRow input{width:100%}.cloudActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}@media(max-width:720px){.cloudTopActions{justify-content:flex-start;margin-top:8px}.cloudModal{top:auto;right:14px;left:14px;bottom:14px;width:auto;max-height:78vh}}
`;document.head.appendChild(s)}
function cloudPanel(){injectCloudStyles();const header=document.querySelector('header');if(!header)return;const tag=header.querySelector('.tag');let tools=document.querySelector('.cloudTopActions');if(!tools){tools=document.createElement('div');tools.className='cloudTopActions';if(tag){tag.replaceWith(tools);tools.appendChild(tag)}else header.appendChild(tools)}const btn=document.createElement('button');btn.id='cloudSyncButton';btn.type='button';btn.className='cloudTopBtn';btn.textContent='☁ Cloud Sync';tools.appendChild(btn);const backdrop=document.createElement('div');backdrop.className='cloudBackdrop';backdrop.id='cloudBackdrop';const modal=document.createElement('section');modal.className='cloudModal';modal.id='cloudModal';modal.innerHTML=`<div class="cloudModalHead"><h2>☁ Cloud Sync</h2><button class="cloudClose" id="cloudClose" type="button">×</button></div><div id="cloudState" class="status">กำลังเช็ก Cloudflare…</div><label class="cloudKeyRow">Admin key <input id="cloudAdmin" type="password" autocomplete="off" placeholder="ADMIN_KEY จาก Cloudflare"></label><div class="cloudActions"><button id="cloudSaveKey" class="ghost" type="button">ใช้ key นี้</button><button id="cloudPull" class="ghost" type="button">โหลดจาก Cloud</button><button id="cloudPush" class="primary" type="button">อัปข้อมูลเครื่องนี้ขึ้น Cloud</button></div><p class="cloudHint">คีย์เก็บเฉพาะ session ของแท็บนี้ ส่วน product cards เก็บใน D1 และรูปเก็บใน R2; localStorage ยังเป็น cache สำรอง</p>`;document.body.append(backdrop,modal);const open=()=>{backdrop.classList.add('open');modal.classList.add('open');document.getElementById('cloudAdmin').value=adminKey()};const close=()=>{backdrop.classList.remove('open');modal.classList.remove('open')};btn.onclick=open;backdrop.onclick=close;document.getElementById('cloudClose').onclick=close;document.getElementById('cloudSaveKey').onclick=()=>{sessionStorage.setItem('cw-admin-key',document.getElementById('cloudAdmin').value.trim());cloudMessage('เก็บ Admin key ไว้ใน session นี้แล้ว','ok')};document.getElementById('cloudPull').onclick=()=>cloudLoad(true);document.getElementById('cloudPush').onclick=cloudPushAll}
function fromCloud(p){return{id:p.id,name:p.name,paid:p.paid||0,list:p.list??null,grams:p.grams,a:p.a,b:p.b,img:p.img||'',notes:p.notes||[],density:p.density??1.10,custom:p.custom!==false,shrink:p.shrink??null,maxPour:p.maxPour??null,shore:p.shore||'',workingMinutes:p.workingMinutes??null,cureHours:p.cureHours??null,sourceUrl:p.sourceUrl||'',imageKey:p.imageKey||''}}
function mergeProducts(local,remote){const m=new Map(local.map(x=>[x.id,x]));remote.forEach(x=>m.set(x.id,x));return[...m.values()]}
async function cloudLoad(showMessage=false){try{const r=await fetch('/api/products',{cache:'no-store'});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||`HTTP ${r.status}`);CLOUD.available=true;document.getElementById('cloudSyncButton')?.classList.add('online');const rs=(d.products||[]).filter(x=>x.type==='silicone').map(fromCloud),rr=(d.products||[]).filter(x=>x.type==='resin').map(fromCloud);if(rs.length||rr.length){sils=mergeProducts(sils,rs);ress=mergeProducts(ress,rr);if(!sils.some(x=>x.id===activeSil))activeSil=sils[0]?.id;if(!ress.some(x=>x.id===activeRes))activeRes=ress[0]?.id;save();renderCards();applyProductDefaults();calc();cloudMessage(`เชื่อม Cloudflare แล้ว · พบ ${rs.length+rr.length} รายการบน Cloud`,'ok')}else cloudMessage('เชื่อม Cloudflare แล้ว แต่ D1 ยังว่าง · ใส่ Admin key แล้วกด “อัปข้อมูลเครื่องนี้ขึ้น Cloud”','ok');if(showMessage&&rs.length+rr.length===0)alert('Cloud เชื่อมแล้ว แต่ยังไม่มีสินค้าใน D1 จ้า')}catch(e){CLOUD.available=false;cloudMessage(`ยังเชื่อม Cloudflare API ไม่ได้: ${e.message}`,'bad')}}
async function dataToBlob(dataUrl){const r=await fetch(dataUrl);return await r.blob()}
async function uploadCloudImage(p){if(!p.img||p.img.startsWith('/api/images/')||p.img.startsWith('assets/')||p.img.startsWith('/assets/'))return{url:p.img||'',key:p.imageKey||''};if(!p.img.startsWith('data:image/'))return{url:p.img,key:p.imageKey||''};const blob=await dataToBlob(p.img),form=new FormData();form.append('file',blob,'product.jpg');const r=await fetch('/api/images',{method:'POST',headers:cloudHeaders(false),body:form});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||`image ${r.status}`);return{url:d.url,key:d.key}}
function cloudPayload(p,type,image){return{id:p.id,type:type==='sil'?'silicone':'resin',name:p.name,paid:p.paid||0,list:p.list??null,grams:p.grams,a:p.a,b:p.b,ratioMethod:'weight',density:p.density??null,shrink:type==='sil'?(p.shrink??null):null,shore:p.shore||'',workingMinutes:p.workingMinutes??null,cureHours:p.cureHours??null,maxPour:type==='res'?(p.maxPour??null):null,imageKey:image.key||'',img:image.url||'',notes:p.notes||[],sourceUrl:p.sourceUrl||'',custom:p.custom!==false}}
async function cloudSaveOne(p,type,silent=false){if(!CLOUD.available||!adminKey())return false;try{const image=await uploadCloudImage(p),payload=cloudPayload(p,type,image);const r=await fetch('/api/products',{method:'POST',headers:cloudHeaders(true),body:JSON.stringify(payload)}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||`HTTP ${r.status}`);if(image.url){p.img=image.url;p.imageKey=image.key;save();renderCards()}if(!silent)cloudMessage(`บันทึก ${p.name} ขึ้น Cloud แล้ว`,'ok');return true}catch(e){if(!silent)cloudMessage(`Cloud save ไม่สำเร็จ: ${e.message}`,'bad');return false}}
async function cloudPushAll(){if(!CLOUD.available){cloudMessage('ยังไม่พบ Cloudflare API','bad');return}if(!adminKey()){cloudMessage('ใส่ Admin key แล้วกด “ใช้ key นี้” ก่อนจ้า','bad');return}if(CLOUD.busy)return;CLOUD.busy=true;cloudMessage('กำลังอัป product cards และรูป…');let ok=0,fail=0;for(const p of sils)(await cloudSaveOne(p,'sil',true))?ok++:fail++;for(const p of ress)(await cloudSaveOne(p,'res',true))?ok++:fail++;CLOUD.busy=false;cloudMessage(`อัปขึ้น Cloud เสร็จ ${ok} รายการ${fail?` · พลาด ${fail}`:''}`,fail?'bad':'ok');await cloudLoad()}
async function cloudDelete(type,id){if(!CLOUD.available||!adminKey())return;try{await fetch(`/api/products/${encodeURIComponent(id)}`,{method:'DELETE',headers:cloudHeaders(false)})}catch{}}
const localAddProduct=addProduct;addProduct=async function(type){await localAddProduct(type);const p=active(type);if(p&&p.custom){if(CLOUD.available&&adminKey())await cloudSaveOne(p,type);else if(CLOUD.available)cloudMessage(`${p.name} บันทึกในเครื่องแล้ว · ใส่ Admin key เพื่อ sync Cloud`)}}
document.addEventListener('click',e=>{const b=e.target.closest?.('.delProd');if(!b)return;const{type,id}=b.dataset;setTimeout(()=>cloudDelete(type,id),0)},true);
cloudPanel();cloudLoad();
