const CLOUD={available:false,busy:false};
const adminKey=()=>sessionStorage.getItem('cw-admin-key')||'';
function cloudHeaders(json=false){const h={};if(json)h['content-type']='application/json';if(adminKey())h['x-admin-key']=adminKey();return h}
function cloudPanel(){const aside=document.querySelector('aside.resultCard');if(!aside)return;const el=document.createElement('article');el.className='card';el.innerHTML=`<h2>☁ Cloud Sync</h2><div id="cloudState" class="status">กำลังเช็ก Cloudflare…</div><div class="grid" style="margin-top:12px"><label>Admin key (เฉพาะ session นี้)<input id="cloudAdmin" type="password" autocomplete="off" placeholder="ตั้งใน Cloudflare secret ADMIN_KEY"></label></div><div class="toolbar"><button id="cloudSaveKey" class="ghost">ใช้ key นี้</button><button id="cloudPull" class="ghost">โหลดจาก Cloud</button><button id="cloudPush" class="primary">อัปข้อมูลเครื่องนี้ขึ้น Cloud</button></div><p class="help">รูปและ product cards จะเก็บใน D1 + R2 ส่วน localStorage ยังเป็น cache สำรอง ถ้ายังเปิดผ่าน GitHub Pages ระบบจะใช้ local ต่อไปจนกว่าจะย้ายไป Cloudflare Pages</p>`;aside.appendChild(el);$('cloudAdmin').value=adminKey();$('cloudSaveKey').onclick=()=>{sessionStorage.setItem('cw-admin-key',$('cloudAdmin').value.trim());cloudMessage('เก็บ Admin key ไว้ใน session นี้แล้ว','ok')};$('cloudPull').onclick=()=>cloudLoad(true);$('cloudPush').onclick=cloudPushAll}
function cloudMessage(msg,kind=''){const el=$('cloudState');if(!el)return;el.className='status'+(kind?' '+kind:'');el.textContent=msg}
function fromCloud(p){return {id:p.id,name:p.name,paid:p.paid||0,list:p.list??null,grams:p.grams,a:p.a,b:p.b,img:p.img||'',notes:p.notes||[],density:p.density??1.10,custom:p.custom!==false,shrink:p.shrink??null,maxPour:p.maxPour??null,shore:p.shore||'',workingMinutes:p.workingMinutes??null,cureHours:p.cureHours??null,sourceUrl:p.sourceUrl||'',imageKey:p.imageKey||''}}
function mergeProducts(local,remote){const m=new Map(local.map(x=>[x.id,x]));remote.forEach(x=>m.set(x.id,x));return [...m.values()]}
async function cloudLoad(showMessage=false){try{const r=await fetch('/api/products',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();if(!d.ok)throw new Error(d.error||'API error');CLOUD.available=true;const rs=(d.products||[]).filter(x=>x.type==='silicone').map(fromCloud),rr=(d.products||[]).filter(x=>x.type==='resin').map(fromCloud);if(rs.length||rr.length){sils=mergeProducts(sils,rs);ress=mergeProducts(ress,rr);if(!sils.some(x=>x.id===activeSil))activeSil=sils[0]?.id;if(!ress.some(x=>x.id===activeRes))activeRes=ress[0]?.id;save();renderCards();applyProductDefaults();calc();cloudMessage(`เชื่อม Cloudflare แล้ว · พบ ${rs.length+rr.length} รายการบน Cloud`,'ok')}else cloudMessage('เชื่อม Cloudflare แล้ว แต่ D1 ยังว่าง · ใส่ Admin key แล้วกด “อัปข้อมูลเครื่องนี้ขึ้น Cloud”','ok');if(showMessage&&rs.length+rr.length===0)alert('Cloud เชื่อมแล้ว แต่ยังไม่มีสินค้าใน D1 จ้า')}catch(e){CLOUD.available=false;cloudMessage('ยังไม่เชื่อม Cloudflare API · ตอนนี้ใช้ localStorage ตามเดิม');}}
async function dataToBlob(dataUrl){const r=await fetch(dataUrl);return await r.blob()}
async function uploadCloudImage(p){if(!p.img||p.img.startsWith('/api/images/')||p.img.startsWith('assets/')||p.img.startsWith('/assets/'))return {url:p.img||'',key:p.imageKey||''};if(!p.img.startsWith('data:image/'))return {url:p.img,key:p.imageKey||''};const blob=await dataToBlob(p.img),form=new FormData();form.append('file',blob,'product.jpg');const r=await fetch('/api/images',{method:'POST',headers:cloudHeaders(false),body:form});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||`image ${r.status}`);return {url:d.url,key:d.key}}
function cloudPayload(p,type,image){return {id:p.id,type:type==='sil'?'silicone':'resin',name:p.name,paid:p.paid||0,list:p.list??null,grams:p.grams,a:p.a,b:p.b,ratioMethod:'weight',density:p.density??null,shrink:type==='sil'?(p.shrink??null):null,shore:p.shore||'',workingMinutes:p.workingMinutes??null,cureHours:p.cureHours??null,maxPour:type==='res'?(p.maxPour??null):null,imageKey:image.key||'',img:image.url||'',notes:p.notes||[],sourceUrl:p.sourceUrl||'',custom:p.custom!==false}}
async function cloudSaveOne(p,type,silent=false){if(!CLOUD.available||!adminKey())return false;try{const image=await uploadCloudImage(p),payload=cloudPayload(p,type,image);const r=await fetch('/api/products',{method:'POST',headers:cloudHeaders(true),body:JSON.stringify(payload)}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||`HTTP ${r.status}`);if(image.url){p.img=image.url;p.imageKey=image.key;save();renderCards()}if(!silent)cloudMessage(`บันทึก ${p.name} ขึ้น Cloud แล้ว`,'ok');return true}catch(e){if(!silent)cloudMessage(`Cloud save ไม่สำเร็จ: ${e.message}`,'bad');return false}}
async function cloudPushAll(){if(!CLOUD.available){cloudMessage('ยังไม่พบ Cloudflare API — ต้อง deploy ผ่าน Cloudflare Pages ก่อน','bad');return}if(!adminKey()){cloudMessage('ใส่ Admin key ก่อนจ้า','bad');return}if(CLOUD.busy)return;CLOUD.busy=true;cloudMessage('กำลังอัป product cards และรูป…');let ok=0,fail=0;for(const p of sils)(await cloudSaveOne(p,'sil',true))?ok++:fail++;for(const p of ress)(await cloudSaveOne(p,'res',true))?ok++:fail++;CLOUD.busy=false;cloudMessage(`อัปขึ้น Cloud เสร็จ ${ok} รายการ${fail?` · พลาด ${fail}`:''}`,fail?'bad':'ok');await cloudLoad()}
async function cloudDelete(type,id){if(!CLOUD.available||!adminKey())return;try{await fetch(`/api/products/${encodeURIComponent(id)}`,{method:'DELETE',headers:cloudHeaders(false)})}catch{}}
const localAddProduct=addProduct;addProduct=async function(type){await localAddProduct(type);const p=active(type);if(p&&p.custom){if(CLOUD.available&&adminKey())await cloudSaveOne(p,type);else if(CLOUD.available)cloudMessage(`${p.name} บันทึกในเครื่องแล้ว · ใส่ Admin key เพื่อ sync Cloud`)}}
document.addEventListener('click',e=>{const b=e.target.closest?.('.delProd');if(!b)return;const {type,id}=b.dataset;setTimeout(()=>cloudDelete(type,id),0)},true);
cloudPanel();cloudLoad();
